### ISSUE TITLE
Select2 update with the CSS classes

### ISSUE THREAD

**Issue by kevin-brown** [select2/select2-bootstrap-theme#3] opened 2015-04-06 02:04 UTC
You can now have Select2 copy over the container CSS classes using the old `containerCssClass` method. You can specify `:all:` to have Select2 copy over all classes on the container, similar to what it used to do.

This requires the full build, and it's only available on master at the moment. I have no idea when I'm going to be finalizing this release, but I _hope_ it's soon.

**Comment by fk** [comment] 2015-04-06 03:20
Just seeing this after [commenting](https://github.com/select2/select2/issues/2879#issuecomment-89895225) some minutes ago – thanks for addressing this so quickly Kevin! I'll switch the demo pages back to the full build then (and remove my [cool button](http://fk.github.io/select2-bootstrap-theme/4.0.0-rc.2.html#why-are-some-select2s-not-scaled) ;-)).

Don't be too quick with the releases – I still need time for the theme. ;-P

**Comment by fk** [comment] 2015-04-29 17:29
@kevin-brown Finally got around to take a look at this; with `containerCssClass: ':all:'` in place and the original element being `<select id="select2-multiple-input-sm" class="form-control input-sm select2-multiple" multiple dir="rtl">`, the CSS classes are copied, but not as expected to the `.select2-container`, but to `.select2-selection` instead:

```
<span class="select2 select2-container select2-container--bootstrap" dir="ltr">
    <span class="selection">
        <span class="select2-selection select2-selection--single form-control input-sm :" role="combobox" aria-autocomplete="list" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-select2-single-input-sm-container">
            …
```

Please note that `.select2-multiple` is a class that I added solely for distinguishing among the various Select2 demos (same goes for the ID); it's not important at all, but it does not seem to get copied. Plus, there's a trailing colon showing up after the copied CSS classes that I can not make sense of.

**Comment by kevin-brown** [comment] 2015-04-29 19:09
> The CSS classes are copied, but not as expected to the .select2-container, but to .select2-selection instead

Right now the current logic in more in line with what actually was happening previously. The problem is that the concept of `container` has changed between Select2 3.x and 4.x. It used to mean "the [selection] container", now it means "the container which holds everything".

Part of the problem is that we [clone all container classes](https://github.com/select2/select2/blob/b1a6d357f95e1788ae7505c9e85ecd987cfd5ac7/src/js/select2/dropdown/attachBody.js#L48-L49) to both the selection and dropdown container, which is not in line with the old `containerCss*` options.

> Plus, there's a trailing colon showing up after the copied CSS classes that I can not make sense of.

Sounds like a bug, want to create a ticket for that?

3.x test case: http://jsbin.com/lovaxetalo/1/edit
4.x test case: http://jsbin.com/lovaxetalo/2/edit

**Comment by fk** [comment] 2016-06-06 15:18
Closing as duplicate of #34.

@kevin-brown

> Sounds like a bug, want to create a ticket for that?

The described issue isn't present in the latest release of Select2, v4.0.3,  anymore: CSS classes prefixed with `select2-` (and assigned to the original `<select>`-element) do not result in a trailing colon with the `containerCssClass` set to `:all:`.

**Closed as completed by fk** 2016-06-06 15:18 UTC
