### ISSUE TITLE
the length is not shinked when shrink the windows

### ISSUE THREAD

**Issue by yelliver** [select2/select2-bootstrap-theme#24] opened 2015-09-11 04:16 UTC
![untitled](https://cloud.githubusercontent.com/assets/1596947/9806976/81f07c7e-5876-11e5-87cf-bb28859a73cc.png)

**Comment by kevin-brown** [comment] 2015-09-11 19:06
This is pretty much a duplicate of https://github.com/select2/select2-bootstrap-theme/issues/2.

**Closed as completed by kevin-brown** 2015-09-11 19:06 UTC
