### ISSUE TITLE
Dropdown width over-/underflow

### ISSUE THREAD

**Issue by Ra1ningSn0w** [select2/select2-bootstrap-theme#33] opened 2016-03-02 13:26 UTC
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2 (not tested)
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Create a horizontal boostrap form with a select input inside a div-tag with col-md-x option
2. Open select input
## Expected behavior and actual behavior

When I follow those steps, I see...
a 1-pixel width under-/overflow

I was expecting...
no under-/overflow
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Microsoft Edge

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 2.2.0
- Select2 version: 4.0.1
- Bootstrap version: 3.3.6
- Bootstrap-Theme version: master
## Isolating the problem
- [x] This bug happens [on the examples page](http://select2.github.io/select2-bootstrap-theme/4.0.0.html) (see col-md-3)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)
## Example

![overflow](https://cloud.githubusercontent.com/assets/2140151/13462852/c8583648-e089-11e5-8416-d415905b8000.png)

**Comment by kevin-brown** [comment] 2016-03-10 15:17
This is a cross-repository duplicate of https://github.com/select2/select2/issues/4224.

**Closed as completed by kevin-brown** 2016-03-10 15:17 UTC
Labels: bug
